server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:classpath:application-${spring.profiles.active}-private.yml
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: ${app.nacos.server-addr:127.0.0.1:8848}
        namespace: ${app.nacos.namespace:}
        group: ${app.nacos.group:DEFAULT_GROUP}
      config:
        enabled: false
        server-addr: ${app.nacos.server-addr:127.0.0.1:8848}
        namespace: ${app.nacos.namespace:}
        group: ${app.nacos.group:DEFAULT_GROUP}
        file-extension: yaml
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/product/**
              filters:
                - StripPrefix=2
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/v1/cart/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order/**
              filters:
                - StripPrefix=2
            - id: stock-service
              uri: lb://stock-service
              predicates:
                - Path=/api/v1/stock/**
              filters:
                - StripPrefix=2
            - id: coupon-service
              uri: lb://coupon-service
              predicates:
                - Path=/api/v1/coupon/**
              filters:
                - StripPrefix=2
management:
  endpoints:
    web:
      exposure:
        include: health,info
