server:
  port: 8083

spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
