version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sparkle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sparkle_shop
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: sparkle-redis
    ports:
      - "6379:6379"

  nacos:
    image: nacos/nacos-server:v2.4.2
    container_name: sparkle-nacos
    environment:
      MODE: standalone
      TZ: Asia/Shanghai
    ports:
      - "8848:8848"
